# List of companies to initialize the crawler with
# Each company should have a name and website URL
companies:
  - name: "Igenius"
    url: "https://www.igenius.ai"
  - name: "Prima"
    url: "https://www.prima.it"
  - name: "Casavo"
    url: "https://www.casavo.com"
  - name: "Xtreamers"
    url: "https://xtreamers.io"
  - name: "agilelab"
    url: "https://www.agilelab.it"
  - name: "Satispay"  
    url: "https://www.satispay.com/it-it"
  - name: "weroad"
    url: "https://www.weroad.it"
  - name: "intella"
    url: "https://www.intella.tech/"